version: '3.8'

volumes:
  postgres_data:
  staticfiles:
  media:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
    - 5432:5432
    env_file:
      - ./.env

  web:
    image: polik/foodgram.v1
    restart: always
    volumes:
      - staticfiles:/code/static
      - media:/code/media
    depends_on:
      - db
    ports:
    - 9000:9000
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.5
    volumes:
      - staticfiles:/static
      - media:/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80
    depends_on:
      - web
