version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data1/
    env_file:
      - ./.env

  web:
    image: polik/foodgram.v1
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    image: nginx:1.19.5
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80
    depends_on:
      - web
