version: '3.8'

volumes:
  postgres_data:
  staticfiles:
  media:

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: polik/foodgram-project.v1
    restart: always
    volumes:
      - staticfiles:/code/static
      - media:/code/media
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.5
    volumes:
      - staticfiles:/code/static
      - media:/code/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80
    depends_on:
      - web